# Generated by Django 5.1.1 on 2024-10-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
